# Generated by Django 4.2.7 on 2024-02-27 11:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "token",
                    models.CharField(
                        default="b2d3b00f-86ae-4004-82a9-52dbc55ad624", max_length=255
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт",
                "verbose_name_plural": "Аккаунты",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("отп. и розн. т", "Оптовая и розничная торговля"),
                            ("it", "IT"),
                            ("трен. и консалт.", "Тренинг, консалтинг"),
                            ("туризм", "Туризм"),
                            ("промышленность", "Промышленность"),
                            ("маркет. и реклама", "Маркетинг, реклама"),
                            ("другое", "Другое"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ген. директор", "Генеральный директор"),
                            ("менеджер", "Менеджер"),
                            ("it спец.", "IT специалист"),
                            ("руководитель отдела", "Руководитель отдела"),
                            ("другое", "Другое"),
                        ],
                        max_length=255,
                    ),
                ),
                ("people", models.IntegerField()),
                ("links", models.JSONField(default=users.models.default_links)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="ProfileMail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_act_profile", models.BooleanField(default=False)),
                ("email_name_profile", models.CharField(max_length=255)),
                (
                    "email_backend",
                    models.CharField(
                        default="django.core.mail.backends.smtp.EmailBackend",
                        max_length=255,
                    ),
                ),
                (
                    "email_file_path",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("email_host", models.CharField(max_length=255)),
                ("email_host_password", models.CharField(max_length=255)),
                ("email_host_user", models.CharField(max_length=255)),
                ("email_port", models.IntegerField(default=0)),
                (
                    "email_subject_prefix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_use_localtime", models.BooleanField(default=False)),
                ("email_use_tls", models.BooleanField(default=True)),
                ("email_use_ssl", models.BooleanField(default=False)),
                (
                    "email_ssl_certfile",
                    models.FileField(blank=True, default=None, null=True, upload_to=""),
                ),
                (
                    "email_ssl_keyfile",
                    models.FileField(blank=True, default=None, null=True, upload_to=""),
                ),
                ("email_timeout", models.IntegerField(default=0)),
                ("email_from_email", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Профиль почтового центра",
                "verbose_name_plural": "Профили почтового центра",
                "db_table": "rs_platform_mails_profile",
                "ordering": ["email_name_profile"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        default="default/default.jpg", upload_to="user_images"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid phone number",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.account"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профаил",
                "verbose_name_plural": "Профайлы",
            },
        ),
    ]
